current_profile: CMCC
profiles:
  CMCC:
    base: http://192.168.200.2:801/eportal/?c=Portal&a=
    login: "login&callback=dr1003&login_method=1&user_account=%2C{device}%2C{account}%40{operator}&user_password={password}&wlan_user_ip={ip}"
    unbind: "unbind_mac&callback=dr1002&user_account={account}%40{operator}&wlan_user_mac=000000000000&wlan_user_ip={ip}"
  CQU:
    base: https://login.cqu.edu.cn:802/eportal/portal/
    login: "login?callback=dr1004&user_account=,{device},{account}&user_password={password}&wlan_user_ip={ip}"
    logout: "logout?callback=dr1006&wlan_user_ip={ip}"
    unbind: "mac/unbind?callback=dr1005&user_account={account}&wlan_user_ip={ip}"
user_info:
  account: xxxx
  password: xxxxx
  operator: cmcc
  device: 1
 